name: Lint & Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
      with:
        node-version: '20.x'
    - run: npm install -g npm@10
    - run: npm ci
    - run: npm run build && npm run build:dev
